services:
  database:
    container_name: database
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database"]
      interval: 10s
      retries: 5
    restart: always
    env_file: .env
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=alankalkan0
      - MYSQL_PASSWORD=alankalkan0
      - MYSQL_DATABASE=nutrimate
      - MYSQL_INITDB_CHARSET=utf8mb4
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  nutrimate-server:
    container_name: nutrimate-server
    build: .
    image: node:18
    depends_on:
      database:
        condition: service_healthy
    env_file: .env
    environment:
      - DB_HOST=database
      - MYSQL_ROOT_PASSWORD=alankalkan0
      - MYSQL_PASSWORD=alankalkan0
      - DATABASE_URL=mysql://root:alankalkan0@database:3306/nutrimate
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma generate && npx prisma migrate dev --schema=/app/prisma/schema.prisma && npm run dev"
    networks:
      - app-network
networks:
  app-network:

volumes:
  db: