services:
  database:
    container_name: database
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database"]
      interval: 10s
      retries: 5
    restart: always
    # env_file: ./.env
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=new_password
      - MYSQL_PASSWORD=new_password
      - MYSQL_DATABASE=nutrimate
      - MYSQL_INITDB_CHARSET=utf8mb4
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  nutrimate-server:
    container_name: nutrimate-server
    build: ./
    image: node:18
    depends_on:
      database:
        condition: service_healthy
    # env_file: ./.env
    environment:
      - DB_HOST=database
      - MYSQL_ROOT_PASSWORD=new_password
      - MYSQL_PASSWORD=new_password
      - DATABASE_URL=mysql://root:new_password@database:3306/nutrimate
    ports:
      - "3000:3000"
    volumes:
      - ./:/workdir
      - /workdir/node_modules
    command: >
      sh -c "npx prisma generate && npx prisma migrate dev --schema=/workdir/prisma/schema.prisma"
    networks:
      - app-network
networks:
  app-network:

volumes:
  db: