networks:
  app-network:
    driver: bridge
services:
  nutrimate-database:
    container_name: nutrimate-database
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "nutrimate-database"]
      interval: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network
    env_file: ./.env
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=alankalkan0
      - MYSQL_PASSWORD=alankalkan0
      - MYSQL_DATABASE=nutrimate
      - MYSQL_INITDB_CHARSET=utf8mb4
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql

  nutrimate-server:
    container_name: nutrimate-server
    build: ./
    image: node:18
    depends_on:
      nutrimate-database:
        condition: service_healthy
    networks:
      - app-network
    env_file: ./.env
    environment:
      - DB_HOST=nutrimate-database
      - MYSQL_ROOT_PASSWORD=alankalkan0
      - MYSQL_PASSWORD=alankalkan0
    ports:
      - "3000:3000"
    volumes:
      - ./:/workdir
      - /workdir/node_modules
    command: >
      sh -c "npx prisma generate && npx prisma migrate dev --schema=/workdir/prisma/schema.prisma"



volumes:
  db: