name: Expo CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test Expo App
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: client
        run: npm install

      # 4. Run tests
      - name: Run tests
        working-directory: client
        run: npm test

      # 5. Login to EAS
      - name: Login to EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        working-directory: client
        run: eas login --token $EXPO_TOKEN

      # 6. Build APK for Android
      - name: Build Android APK
        working-directory: client
        run: eas build --platform android --profile production --non-interactive

      # 7. Upload artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: client/build/*.apk
